# FT-Transformer

In [1]:
!python -m pip install --upgrade pip setuptools wheel

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: pip in /root/miniconda3/lib/python3.10/site-packages (26.1.1)
Requirement already satisfied: setuptools in /root/miniconda3/lib/python3.10/site-packages (82.0.1)
Requirement already satisfied: wheel in /root/miniconda3/lib/python3.10/site-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in /root/miniconda3/lib/python3.10/site-packages (from wheel) (26.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [2]:
!pip install ipywidgets

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: ipywidgets in /root/miniconda3/lib/python3.10/site-packages (8.1.1)
Requirement already satisfied: comm>=0.1.3 in /root/miniconda3/lib/python3.10/site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in /root/miniconda3/lib/python3.10/site-packages (from ipywidgets) (8.20.0)
Requirement already satisfied: traitlets>=4.3.1 in /root/miniconda3/lib/python3.10/site-packages (from ipywidgets) (5.14.1)
Requirement already satisfied: widgetsnbextension~=4.0.9 in /root/miniconda3/lib/python3.10/site-packages (from ipywidgets) (4.0.9)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in /root/miniconda3/lib/python3.10/site-packages (from ipywidgets) (3.0.9)
Requirement already satisfied: decorator in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.17.2)
Requirement already satisfied: stack-data in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: exceptiongroup in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: pexpect>4.3 in /root/miniconda3/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: wcwidth in /root/miniconda3/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /root/miniconda3/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /root/miniconda3/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /root/miniconda3/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /root/miniconda3/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /root/miniconda3/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /root/miniconda3/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [3]:
!pip install rtdl_revisiting_models -q

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [4]:
import pandas as pd
import numpy as np
import os

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from rtdl_revisiting_models import FTTransformer

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
DATA_PATH = "FeatureB_Repeated"
OUTPUT_PATH = "Official_FTTransformer_FeatureB_Results"


os.makedirs(OUTPUT_PATH, exist_ok=True)

N_REPEATS = 10

cuda

In [6]:
def get_feature_cols(df):
    return [
        col for col in df.columns
        if col not in ["userId", "movieId", "label"]
    ]

In [7]:
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [8]:
def compute_auc_from_scratch(y_true, y_score):
    y_true = np.array(y_true)
    y_score = np.array(y_score)

    sorted_indices = np.argsort(-y_score)
    y_true_sorted = y_true[sorted_indices]

    pos_count = np.sum(y_true == 1)
    neg_count = np.sum(y_true == 0)

    if pos_count == 0 or neg_count == 0:
        return 0

    tp = 0
    fp = 0

    tpr_list = [0]
    fpr_list = [0]

    for label in y_true_sorted:
        if label == 1:
            tp += 1
        else:
            fp += 1

        tpr_list.append(tp / pos_count)
        fpr_list.append(fp / neg_count)

    auc = 0

    for i in range(1, len(tpr_list)):
        auc += (
            (fpr_list[i] - fpr_list[i - 1])
            * (tpr_list[i] + tpr_list[i - 1])
            / 2
        )

    return auc


def compute_metrics_from_scratch(y_true, y_pred, y_score):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))

    accuracy = (tp + tn) / len(y_true)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0
    )

    auc = compute_auc_from_scratch(y_true, y_score)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "auc": auc,
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn
    }

In [9]:
def stratified_sample_binary(df, sample_size, random_seed):
    if sample_size >= len(df):
        return df.sample(frac=1, random_state=random_seed).reset_index(drop=True)

    sample_ratio = sample_size / len(df)

    sampled_df = (
        df
        .groupby("label", group_keys=False)
        .apply(
            lambda x: x.sample(
                n=max(1, int(len(x) * sample_ratio)),
                random_state=random_seed
            )
        )
        .sample(frac=1, random_state=random_seed)
        .reset_index(drop=True)
    )

    return sampled_df

In [10]:
def stratified_split_from_scratch(df, label_col, test_ratio=0.2, random_seed=42):
    rng = np.random.default_rng(random_seed)

    train_indices = []
    test_indices = []

    for label_value in df[label_col].unique():
        label_indices = df[df[label_col] == label_value].index.to_numpy()
        rng.shuffle(label_indices)

        test_size = int(len(label_indices) * test_ratio)

        test_indices.extend(label_indices[:test_size])
        train_indices.extend(label_indices[test_size:])

    train_df = df.loc[train_indices].sample(
        frac=1,
        random_state=random_seed
    ).reset_index(drop=True)

    test_df = df.loc[test_indices].sample(
        frac=1,
        random_state=random_seed
    ).reset_index(drop=True)

    return train_df, test_df

In [11]:
def train_official_ft_transformer(
    train_df,
    test_df,
    lr=1e-4,
    weight_decay=1e-5,
    batch_size=4096,
    epochs=3
):
    feature_cols = get_feature_cols(train_df)

    X_train = train_df[feature_cols].values
    y_train = train_df["label"].values

    X_test = test_df[feature_cols].values
    y_test = test_df["label"].values

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    train_dataset = TabularDataset(X_train, y_train)
    test_dataset = TabularDataset(X_test, y_test)

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False
    )

    model = FTTransformer(
        n_cont_features=len(feature_cols),
        cat_cardinalities=[],
        d_out=1,
        **FTTransformer.get_default_kwargs()
    ).to(device)

    optimizer = model.make_default_optimizer()
    
    # Override default optimizer lr / weight_decay if needed
    for group in optimizer.param_groups:
        group["lr"] = lr
        group["weight_decay"] = weight_decay

    criterion = nn.BCEWithLogitsLoss()

    model.train()

    for epoch in range(epochs):
        total_loss = 0

        for batch_X, batch_y in train_loader:
            batch_X = batch_X.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()

            logits = model(batch_X, None).squeeze(1)

            loss = criterion(logits, batch_y)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch + 1} loss:", round(total_loss, 4))

    model.eval()

    all_preds = []
    all_scores = []
    all_labels = []

    with torch.no_grad():
        for batch_X, batch_y in test_loader:
            batch_X = batch_X.to(device)

            logits = model(batch_X, None).squeeze(1)
            probs = torch.sigmoid(logits)

            preds = (probs >= 0.5).int()

            all_preds.extend(preds.detach().cpu().tolist())
            all_scores.extend(probs.detach().cpu().tolist())
            all_labels.extend(batch_y.detach().cpu().tolist())

    metrics = compute_metrics_from_scratch(
        all_labels,
        all_preds,
        all_scores
    )

    return metrics

In [12]:
TRAIN_SAMPLE_SIZE = 30000
TEST_SAMPLE_SIZE = 10000

LR_VALUES = [5e-5, 1e-4, 5e-4]
WEIGHT_DECAY_VALUES = [1e-5]

N_INNER_REPEATS = 3
VALID_RATIO = 0.2

BATCH_SIZE = 1024
EPOCHS = 3

all_results = []
all_tuning_results = []

for repeat_id in range(1, N_REPEATS + 1):
    print("=" * 60)
    print(f"Outer Repeat {repeat_id:02d}")
    print("=" * 60)

    repeat_folder = os.path.join(
        DATA_PATH,
        f"repeat_{repeat_id:02d}"
    )

    train_path = os.path.join(repeat_folder, "feature_B_train.csv")
    test_path = os.path.join(repeat_folder, "feature_B_test.csv")

    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)

    train_df = stratified_sample_binary(
        train_df,
        sample_size=TRAIN_SAMPLE_SIZE,
        random_seed=42 + repeat_id
    )

    test_df = stratified_sample_binary(
        test_df,
        sample_size=TEST_SAMPLE_SIZE,
        random_seed=100 + repeat_id
    )

    print("Outer train shape:", train_df.shape)
    print("Outer test shape:", test_df.shape)

    best_lr = None
    best_weight_decay = None
    best_mean_val_f1 = -1

    for lr in LR_VALUES:
        for weight_decay in WEIGHT_DECAY_VALUES:

            inner_f1_scores = []

            for inner_id in range(N_INNER_REPEATS):
                inner_train_df, val_df = stratified_split_from_scratch(
                    train_df,
                    label_col="label",
                    test_ratio=VALID_RATIO,
                    random_seed=2000 + repeat_id * 10 + inner_id
                )

                print(
                    f"Trying lr={lr}, weight_decay={weight_decay}, inner={inner_id + 1}"
                )

                val_metrics = train_official_ft_transformer(
                    train_df=inner_train_df,
                    test_df=val_df,
                    lr=lr,
                    weight_decay=weight_decay,
                    batch_size=BATCH_SIZE,
                    epochs=EPOCHS
                )

                inner_f1_scores.append(val_metrics["f1"])

            mean_val_f1 = np.mean(inner_f1_scores)
            std_val_f1 = np.std(inner_f1_scores, ddof=1)

            all_tuning_results.append({
                "outer_repeat": repeat_id,
                "lr": lr,
                "weight_decay": weight_decay,
                "mean_validation_f1": mean_val_f1,
                "std_validation_f1": std_val_f1
            })

            print("Mean validation F1:", round(mean_val_f1, 6))

            if mean_val_f1 > best_mean_val_f1:
                best_mean_val_f1 = mean_val_f1
                best_lr = lr
                best_weight_decay = weight_decay

    print("Best lr:", best_lr)
    print("Best weight_decay:", best_weight_decay)
    print("Best mean validation F1:", best_mean_val_f1)

    test_metrics = train_official_ft_transformer(
        train_df=train_df,
        test_df=test_df,
        lr=best_lr,
        weight_decay=best_weight_decay,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS
    )

    final_result = {
        "repeat": repeat_id,
        "best_lr": best_lr,
        "best_weight_decay": best_weight_decay,
        "batch_size": BATCH_SIZE,
        "best_mean_val_f1": best_mean_val_f1,
        **test_metrics
    }

    all_results.append(final_result)

    print("Accuracy :", round(test_metrics["accuracy"], 4))
    print("Precision:", round(test_metrics["precision"], 4))
    print("Recall   :", round(test_metrics["recall"], 4))
    print("F1       :", round(test_metrics["f1"], 4))
    print("AUC      :", round(test_metrics["auc"], 4))

============================================================
Outer Repeat 01
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.0815
Epoch 2 loss: 8.8415
Epoch 3 loss: 8.1996
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.0488
Epoch 2 loss: 9.0686
Epoch 3 loss: 8.2515
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.3983
Epoch 2 loss: 8.859
Epoch 3 loss: 8.1044
Mean validation F1: 0.84577
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.3631
Epoch 2 loss: 8.3708
Epoch 3 loss: 7.7817
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.1164
Epoch 2 loss: 8.5089
Epoch 3 loss: 7.6984
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.2595
Epoch 2 loss: 8.8302
Epoch 3 loss: 7.9607
Mean validation F1: 0.852409
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.6924
Epoch 2 loss: 8.0003
Epoch 3 loss: 7.4354
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.3153
Epoch 2 loss: 7.885
Epoch 3 loss: 7.2889
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.2802
Epoch 2 loss: 8.1596
Epoch 3 loss: 7.4849
Mean validation F1: 0.852017
Best lr: 0.0001
Best weight_decay: 1e-05
Best mean validation F1: 0.8524094519726826
Epoch 1 loss: 14.0426
Epoch 2 loss: 10.1831
Epoch 3 loss: 9.4636
Accuracy : 0.6444
Precision: 0.6338
Recall   : 0.683
F1       : 0.6575
AUC      : 0.6601
============================================================
Outer Repeat 02
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.294
Epoch 2 loss: 8.8289
Epoch 3 loss: 8.0818
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.4008
Epoch 2 loss: 8.8521
Epoch 3 loss: 8.2454
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.4911
Epoch 2 loss: 8.8004
Epoch 3 loss: 8.1186
Mean validation F1: 0.854743
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.767
Epoch 2 loss: 8.579
Epoch 3 loss: 7.8078
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.7603
Epoch 2 loss: 9.0932
Epoch 3 loss: 8.1052
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.1497
Epoch 2 loss: 8.254
Epoch 3 loss: 7.5709
Mean validation F1: 0.852994
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.5775
Epoch 2 loss: 7.7557
Epoch 3 loss: 7.3799
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.7656
Epoch 2 loss: 8.2853
Epoch 3 loss: 7.5341
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.3523
Epoch 2 loss: 8.0428
Epoch 3 loss: 7.355
Mean validation F1: 0.855173
Best lr: 0.0005
Best weight_decay: 1e-05
Best mean validation F1: 0.855173038401786
Epoch 1 loss: 15.6772
Epoch 2 loss: 9.6335
Epoch 3 loss: 9.1057
Accuracy : 0.6187
Precision: 0.6358
Recall   : 0.5547
F1       : 0.5925
AUC      : 0.6362
============================================================
Outer Repeat 03
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.9864
Epoch 2 loss: 8.7791
Epoch 3 loss: 8.1174
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.0381
Epoch 2 loss: 9.1226
Epoch 3 loss: 8.2305
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 13.8398
Epoch 2 loss: 9.1213
Epoch 3 loss: 8.231
Mean validation F1: 0.848234
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.9666
Epoch 2 loss: 8.5764
Epoch 3 loss: 7.9069
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.2904
Epoch 2 loss: 8.4583
Epoch 3 loss: 7.7168
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.2579
Epoch 2 loss: 8.3895
Epoch 3 loss: 7.6805
Mean validation F1: 0.848638
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.4612
Epoch 2 loss: 8.2681
Epoch 3 loss: 7.5337
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.2322
Epoch 2 loss: 7.8685
Epoch 3 loss: 7.2895
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.5769
Epoch 2 loss: 8.2852
Epoch 3 loss: 7.4984
Mean validation F1: 0.839928
Best lr: 0.0001
Best weight_decay: 1e-05
Best mean validation F1: 0.8486376763187282
Epoch 1 loss: 14.1631
Epoch 2 loss: 10.2525
Epoch 3 loss: 9.4484
Accuracy : 0.6467
Precision: 0.635
Recall   : 0.6892
F1       : 0.661
AUC      : 0.6675
============================================================
Outer Repeat 04
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.8261
Epoch 2 loss: 8.752
Epoch 3 loss: 8.1123
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.3086
Epoch 2 loss: 8.8421
Epoch 3 loss: 8.1675
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.7391
Epoch 2 loss: 8.8921
Epoch 3 loss: 8.1817
Mean validation F1: 0.855248
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.6109
Epoch 2 loss: 8.5932
Epoch 3 loss: 7.8352
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.0996
Epoch 2 loss: 8.2171
Epoch 3 loss: 7.6891
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.8893
Epoch 2 loss: 8.4035
Epoch 3 loss: 7.769
Mean validation F1: 0.85058
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.5787
Epoch 2 loss: 8.2094
Epoch 3 loss: 7.5521
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 10.8951
Epoch 2 loss: 7.6885
Epoch 3 loss: 7.357
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.6161
Epoch 2 loss: 7.9349
Epoch 3 loss: 7.3373
Mean validation F1: 0.844619
Best lr: 5e-05
Best weight_decay: 1e-05
Best mean validation F1: 0.8552484091102488
Epoch 1 loss: 15.1575
Epoch 2 loss: 10.7562
Epoch 3 loss: 9.9374
Accuracy : 0.636
Precision: 0.6348
Recall   : 0.6396
F1       : 0.6372
AUC      : 0.66
============================================================
Outer Repeat 05
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.1346
Epoch 2 loss: 8.7504
Epoch 3 loss: 8.0827
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.1182
Epoch 2 loss: 8.7683
Epoch 3 loss: 8.0811
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 13.0067
Epoch 2 loss: 9.0581
Epoch 3 loss: 8.2677
Mean validation F1: 0.85027
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.0403
Epoch 2 loss: 8.5162
Epoch 3 loss: 7.7899
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.7093
Epoch 2 loss: 8.6797
Epoch 3 loss: 7.8804
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.2679
Epoch 2 loss: 8.1809
Epoch 3 loss: 7.555
Mean validation F1: 0.849241
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.6768
Epoch 2 loss: 8.1554
Epoch 3 loss: 7.4133
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.1209
Epoch 2 loss: 8.5109
Epoch 3 loss: 7.496
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.9918
Epoch 2 loss: 8.0664
Epoch 3 loss: 7.3627
Mean validation F1: 0.847161
Best lr: 5e-05
Best weight_decay: 1e-05
Best mean validation F1: 0.850269760172416
Epoch 1 loss: 15.4868
Epoch 2 loss: 10.8137
Epoch 3 loss: 9.8927
Accuracy : 0.622
Precision: 0.6505
Recall   : 0.5263
F1       : 0.5819
AUC      : 0.6481
============================================================
Outer Repeat 06
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.0558
Epoch 2 loss: 8.8627
Epoch 3 loss: 8.1466
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.8805
Epoch 2 loss: 9.3428
Epoch 3 loss: 8.464
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 13.8403
Epoch 2 loss: 9.3584
Epoch 3 loss: 8.5614
Mean validation F1: 0.846166
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.1989
Epoch 2 loss: 8.5436
Epoch 3 loss: 7.7331
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.0632
Epoch 2 loss: 8.2598
Epoch 3 loss: 7.6655
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.9844
Epoch 2 loss: 8.5705
Epoch 3 loss: 7.7468
Mean validation F1: 0.849959
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.4546
Epoch 2 loss: 8.0149
Epoch 3 loss: 7.3409
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.8662
Epoch 2 loss: 8.3787
Epoch 3 loss: 7.5275
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.4456
Epoch 2 loss: 8.1559
Epoch 3 loss: 7.6304
Mean validation F1: 0.842793
Best lr: 0.0001
Best weight_decay: 1e-05
Best mean validation F1: 0.8499588187537149
Epoch 1 loss: 13.6259
Epoch 2 loss: 10.1958
Epoch 3 loss: 9.462
Accuracy : 0.639
Precision: 0.6327
Recall   : 0.6618
F1       : 0.6469
AUC      : 0.6531
============================================================
Outer Repeat 07
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.0757
Epoch 2 loss: 8.8788
Epoch 3 loss: 8.2482
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.5401
Epoch 2 loss: 9.0292
Epoch 3 loss: 8.1364
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.9439
Epoch 2 loss: 9.0823
Epoch 3 loss: 8.2923
Mean validation F1: 0.843822
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.6365
Epoch 2 loss: 8.5961
Epoch 3 loss: 7.8194
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.4783
Epoch 2 loss: 8.4519
Epoch 3 loss: 7.7215
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.8293
Epoch 2 loss: 8.4771
Epoch 3 loss: 7.7135
Mean validation F1: 0.8433
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.6103
Epoch 2 loss: 8.353
Epoch 3 loss: 7.6431
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.6344
Epoch 2 loss: 8.481
Epoch 3 loss: 7.4644
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.6833
Epoch 2 loss: 8.1456
Epoch 3 loss: 7.4149
Mean validation F1: 0.841134
Best lr: 5e-05
Best weight_decay: 1e-05
Best mean validation F1: 0.8438222957725294
Epoch 1 loss: 14.2321
Epoch 2 loss: 10.6245
Epoch 3 loss: 9.8764
Accuracy : 0.6338
Precision: 0.6302
Recall   : 0.6464
F1       : 0.6382
AUC      : 0.655
============================================================
Outer Repeat 08
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 13.0068
Epoch 2 loss: 9.0341
Epoch 3 loss: 8.2059
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.6019
Epoch 2 loss: 8.7736
Epoch 3 loss: 8.1549
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 13.0916
Epoch 2 loss: 9.1328
Epoch 3 loss: 8.3918
Mean validation F1: 0.842754
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.9561
Epoch 2 loss: 8.5344
Epoch 3 loss: 7.7796
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 10.7609
Epoch 2 loss: 8.15
Epoch 3 loss: 7.6618
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 10.8957
Epoch 2 loss: 8.1975
Epoch 3 loss: 7.6911
Mean validation F1: 0.850356
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.8158
Epoch 2 loss: 8.2293
Epoch 3 loss: 7.432
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.8686
Epoch 2 loss: 8.2225
Epoch 3 loss: 7.4838
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.1422
Epoch 2 loss: 8.054
Epoch 3 loss: 7.514
Mean validation F1: 0.849102
Best lr: 0.0001
Best weight_decay: 1e-05
Best mean validation F1: 0.8503556017743953
Epoch 1 loss: 13.7321
Epoch 2 loss: 10.2827
Epoch 3 loss: 9.5013
Accuracy : 0.6341
Precision: 0.647
Recall   : 0.5892
F1       : 0.6167
AUC      : 0.6537
============================================================
Outer Repeat 09
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 13.5946
Epoch 2 loss: 9.5552
Epoch 3 loss: 8.6575
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.839
Epoch 2 loss: 9.3263
Epoch 3 loss: 8.3986
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.2737
Epoch 2 loss: 8.8397
Epoch 3 loss: 8.1012
Mean validation F1: 0.842945
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.2377
Epoch 2 loss: 8.6482
Epoch 3 loss: 7.866
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.1271
Epoch 2 loss: 8.2024
Epoch 3 loss: 7.6081
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.6662
Epoch 2 loss: 8.4211
Epoch 3 loss: 7.7024
Mean validation F1: 0.85096
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 12.1644
Epoch 2 loss: 8.2483
Epoch 3 loss: 7.5656
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 12.9607
Epoch 2 loss: 8.0375
Epoch 3 loss: 7.468
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.7486
Epoch 2 loss: 8.0962
Epoch 3 loss: 7.5979
Mean validation F1: 0.835668
Best lr: 0.0001
Best weight_decay: 1e-05
Best mean validation F1: 0.8509595991619952
Epoch 1 loss: 14.3061
Epoch 2 loss: 10.2928
Epoch 3 loss: 9.513
Accuracy : 0.6328
Precision: 0.6579
Recall   : 0.5525
F1       : 0.6006
AUC      : 0.656
============================================================
Outer Repeat 10
============================================================

/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/tmp/ipykernel_8498/3738243803.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Outer train shape: (29999, 122)
Outer test shape: (9999, 122)
Trying lr=5e-05, weight_decay=1e-05, inner=1
Epoch 1 loss: 13.8495
Epoch 2 loss: 9.1408
Epoch 3 loss: 8.2294
Trying lr=5e-05, weight_decay=1e-05, inner=2
Epoch 1 loss: 13.3097
Epoch 2 loss: 8.9522
Epoch 3 loss: 8.2013
Trying lr=5e-05, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.5451
Epoch 2 loss: 8.7794
Epoch 3 loss: 8.0659
Mean validation F1: 0.851296
Trying lr=0.0001, weight_decay=1e-05, inner=1
Epoch 1 loss: 11.5822
Epoch 2 loss: 8.4552
Epoch 3 loss: 7.7959
Trying lr=0.0001, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.9733
Epoch 2 loss: 8.3569
Epoch 3 loss: 7.6861
Trying lr=0.0001, weight_decay=1e-05, inner=3
Epoch 1 loss: 11.6138
Epoch 2 loss: 8.2844
Epoch 3 loss: 7.656
Mean validation F1: 0.852116
Trying lr=0.0005, weight_decay=1e-05, inner=1
Epoch 1 loss: 13.1408
Epoch 2 loss: 8.2403
Epoch 3 loss: 7.5345
Trying lr=0.0005, weight_decay=1e-05, inner=2
Epoch 1 loss: 11.5207
Epoch 2 loss: 7.8412
Epoch 3 loss: 7.3689
Trying lr=0.0005, weight_decay=1e-05, inner=3
Epoch 1 loss: 12.8155
Epoch 2 loss: 8.5144
Epoch 3 loss: 7.5724
Mean validation F1: 0.852168
Best lr: 0.0005
Best weight_decay: 1e-05
Best mean validation F1: 0.852168433876376
Epoch 1 loss: 14.7097
Epoch 2 loss: 9.7864
Epoch 3 loss: 9.1239
Accuracy : 0.6376
Precision: 0.6407
Recall   : 0.6256
F1       : 0.633
AUC      : 0.6526

In [13]:
results_df = pd.DataFrame(all_results)
tuning_results_df = pd.DataFrame(all_tuning_results)

results_path = os.path.join(
    OUTPUT_PATH,
    "FTTransformer_FeatureB_repeated_results.csv"
)

tuning_path = os.path.join(
    OUTPUT_PATH,
    "FTTransformer_FeatureB_tuning_results.csv"
)

results_df.to_csv(results_path, index=False, encoding="utf-8-sig")
tuning_results_df.to_csv(tuning_path, index=False, encoding="utf-8-sig")

print("Saved repeated test results to:")
print(results_path)

print("Saved tuning results to:")
print(tuning_path)

results_df

Saved repeated test results to:
Official_FTTransformer_FeatureB_Results/FTTransformer_FeatureB_repeated_results.csv
Saved tuning results to:
Official_FTTransformer_FeatureB_Results/FTTransformer_FeatureB_tuning_results.csv

,repeat,best_lr,best_weight_decay,batch_size,best_mean_val_f1,accuracy,precision,recall,f1,auc,tp,tn,fp,fn
0,1,0.00010,0.00001,1024,0.852409,0.644364,0.633798,0.683010,0.657484,0.660102,3413,3030,1972,1584
1,2,0.00050,0.00001,1024,0.855173,0.618662,0.635780,0.554733,0.592498,0.636152,2772,3414,1588,2225
2,3,0.00010,0.00001,1024,0.848638,0.646665,0.634956,0.689214,0.660973,0.667483,3444,3022,1980,1553
3,4,0.00005,0.00001,1024,0.855248,0.635964,0.634757,0.639584,0.637161,0.660039,3196,3163,1839,1801
4,5,0.00005,0.00001,1024,0.850270,0.621962,0.650507,0.526316,0.581858,0.648140,2630,3589,1413,2367
5,6,0.00010,0.00001,1024,0.849959,0.638964,0.632676,0.661797,0.646909,0.653092,3307,3082,1920,1690
6,7,0.00005,0.00001,1024,0.843822,0.633763,0.630244,0.646388,0.638214,0.654954,3230,3107,1895,1767
7,8,0.00010,0.00001,1024,0.850356,0.634063,0.647033,0.589153,0.616738,0.653734,2944,3396,1606,2053
8,9,0.00010,0.00001,1024,0.850960,0.632763,0.657851,0.552532,0.600609,0.655972,2761,3566,1436,2236
9,10,0.00050,0.00001,1024,0.852168,0.637564,0.640705,0.625575,0.633050,0.652618,3126,3249,1753,1871

In [14]:
summary_records = []

for metric in ["accuracy", "precision", "recall", "f1", "auc"]:
    values = results_df[metric].values

    summary_records.append({
        "metric": metric,
        "mean": np.mean(values),
        "std": np.std(values, ddof=1),
        "standard_error": np.std(values, ddof=1) / np.sqrt(len(values))
    })

summary_df = pd.DataFrame(summary_records)

summary_path = os.path.join(
    OUTPUT_PATH,
    "FTTransformer_FeatureB_summary.csv"
)

summary_df.to_csv(
    summary_path,
    index=False,
    encoding="utf-8-sig"
)

summary_df

      metric      mean       std  standard_error
0   accuracy  0.634473  0.008747        0.002766
1  precision  0.639831  0.009048        0.002861
2     recall  0.616830  0.057791        0.018275
3         f1  0.626549  0.027433        0.008675
4        auc  0.654229  0.008270        0.002615

In [15]:
# Best learning rate frequency for FT-Transformer

best_lr_frequency = (
    results_df["best_lr"]
    .value_counts()
    .reset_index()
)

best_lr_frequency.columns = ["learning_rate", "frequency"]

best_lr_frequency_path = os.path.join(
    OUTPUT_PATH,
    "FTTransformer_FeatureB_best_lr_frequency.csv"
)

best_lr_frequency.to_csv(
    best_lr_frequency_path,
    index=False,
    encoding="utf-8-sig"
)


best_lr_frequency

   learning_rate  frequency
0        0.00010          5
1        0.00005          3
2        0.00050          2